apiVersion: v1
kind: Service
metadata:
  name: atp-user-producer
  labels:
    app.kubernetes.io/name: atp-user-producer
    app.kubernetes.io/instance: atp-user-producer
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: atp-user-producer
    app.kubernetes.io/instance: atp-user-producer
